import { getSectionScores } from '../../utils/rubric_scores_helper';
import mockRubric from '../mock_data/rubric_mock';


test('can reutrn an array with thesis section scores when given thesis section title', () => {
  expect(getSectionScores('thesis', mockRubric.rubric_items)).toEqual([{ 1: 'Topic sentence partially addresses the prompt and may misinterpret some of the prompt or present superfluous claims. Topic sentence is an opinion, stated in the 1st person.' }, { 2: 'Clear and focused topic sentence generally addresses the prompt and purpose.The topic sentence states a relevant claim in the third person.' }, { 3: 'Thesis statement largely attempts to address all the parts of the prompt, but may lack clarity or specificity and/or may parrot the prompt.' }, { 4: '5th Grade and 6th Grade: Clear, defensible thesis statement addresses all the parts of the prompt. The thesis states a claim in third person.May list assertions in the thesis statement.' }, { 5: 'Clear, defensible, comprehensive thesis statement addresses all the parts of the prompt.The thesis states a claim in third person. May list assertions in the thesis statement.' }, { 6: '7th Grade: Clear, defensible, comprehensive, and focused thesis statement addresses all parts of the prompt. The thesis states a claim in the third person.May list assertions in the thesis statement.' }, { 7: '8th Grade: Clear, defensible, comprehensive, focused, and analytical thesis statement completely addresses the prompt. The thesis states a claim in the third person.' }, { 8: 'Clear, defensible, comprehensive, focused, analytical, and nuanced thesis statement completely addresses the prompt. Thesis supports assertions. The thesis states a claim in the third person.' }]);
});

test('can reutrn an array with evidence section scores when given evidence section title', () => {
  expect(getSectionScores('evidence', mockRubric.rubric_items)).toEqual([{ 1: 'Generally body paragraphs contain topic sentences that frame each paragraph. Some topic sentences are related to the topic of the paper.' }, { 2: 'Most topic sentences are relevant to the topic of the paper.' }, { 3: 'All topic sentences are directly relevant to the topic of the paper.' }, { 4: 'Each topic sentence is directly relevant to the thesis statement and some topic sentences are assertions. Sequence of assertions may be random.' }, { 5: 'Each topic sentence is directly relevant to the thesis and most topic sentences are assertions.Sequence of assertions is attempted.' }, { 6: 'Each topic sentence is an assertion that supports the thesis statement.Sequence of assertions is mostly intentional but may not effectively advance the argument.' }, { 7: 'Each assertion provides defensible and relevant support for the larger argument of the thesis statement. Some assertions are clarified in scope. Sequence of assertions is intentional and sometimes advances the argument.' }, { 8: 'Each assertion provides defensible and relevant support for the larger argument of the thesis statement.Assertions are mostly clarified in scope. Sequence of assertions is intentional and mostly advances the argument.' }]);
});
